import SwiftData
import Foundation

/// VersionedSchema v1.0.0 — the initial schema for the MyHome app.
///
/// All @Model types are nested inside the version enum to prevent namespace
/// collisions when v2 renames or restructures them. Never modify this enum
/// after v1 ships; add a new SchemaV2 enum and a migration stage instead.
///
/// CloudKit-readiness rules enforced (FND-03, ARCHITECTURE.md):
/// 1. Every stored property has a default or is optional.
/// 2. No @Attribute(.unique) anywhere.
/// 3. Decimal for money (never Double).
/// 4. Full UTC timestamp for dates (never date-only).
/// 5. currencyCode: String present for multi-currency-readiness.
/// 6. UUID primary key (not relying on SwiftData hidden persistent ID).
/// 7. All relationships optional with explicit inverse (Phase 2 will add Category).
/// 8. Delete rule .nullify on optional relationships (no .cascade on shared objects).
enum SchemaV1: VersionedSchema {
    static let versionIdentifier = Schema.Version(1, 0, 0)

    static var models: [any PersistentModel.Type] {
        [SchemaV1.Expense.self]
    }

    // MARK: - Expense @Model

    @Model
    final class Expense {
        // No @Attribute(.unique) — CloudKit does not support unique constraints.
        // UUID is generated by us; we own uniqueness via lookup-before-insert.
        var id: UUID = UUID()
        var amount: Decimal = Decimal(0)        // never Double (Pitfall 17)
        var currencyCode: String = "INR"        // schema-forward: multi-currency-ready
        var date: Date = Date()                 // UTC timestamp; format at display time (D-02)
        var note: String? = nil                 // optional free-form memo / payee (D-05, D-06)
        var createdAt: Date = Date()
        var updatedAt: Date = Date()

        // Phase 2 will add:
        // @Relationship(deleteRule: .nullify, inverse: \Category.expenses)
        // var category: Category? = nil

        init(
            id: UUID = UUID(),
            amount: Decimal,
            currencyCode: String = "INR",
            date: Date = Date(),
            note: String? = nil
        ) {
            self.id = id
            self.amount = amount
            self.currencyCode = currencyCode
            self.date = date
            self.note = note
            self.createdAt = Date()
            self.updatedAt = Date()
        }
    }
}
